Revert "ci: temporarily fail all non-docs-related GitHub Actions workflows"
This reverts commit 0190ab13a7b48f2d68234b65f7e9786659729c40.

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -2,7 +2,7 @@ name: Pull Request checks
 
 on:
   pull_request:
-    # Note: each of these ignored paths requires a path entry in pull_request.yml
+    # Note: each of these ignored paths requires a path entry in pull_request_inverted.yml
     paths-ignore:
        - "**.md"
        - ".github/CODEOWNERS"
@@ -12,42 +12,210 @@ on:
     branches:
     - main
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   lint:
     name: 🕵️‍♀️ NPM lint
     runs-on: ubuntu-latest
     steps:
-    - run: exit 1
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 1
+    - uses: actions/setup-node@v4
+      with:
+        node-version: '22.x'
+    - name: Cache node modules
+      uses: actions/cache@v4
+      with:
+        path: node_modules
+        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
+        restore-keys: |
+          ${{ runner.os }}-node-
+    - name: gulp build
+      run: make front_build
+    - name: lint
+      run: make front_lint
 
+  # this will build the docker image and upload as an artifact for following jobs
   build_backend:
     name: 🏗 Build backend dev image for tests
     runs-on: ubuntu-latest
     steps:
-    - run: exit 1
+    - uses: actions/checkout@v4
+      with:
+        # needs depth to run git log below
+        fetch-depth: 50
+    - uses: actions/cache@v4
+      id: cache
+      with:
+        path: ./build-cache
+        key: taxonomies-${{ hashFiles('taxonomies/**') }}
+        restore-keys: taxonomies-
+    - name: build
+      run: make build container=backend
+    - name: push backend image as artifact
+      uses: ishworkh/container-image-artifact-upload@v2.0.0
+      with:
+        image: "openfoodfacts-server/backend:dev"
+    - name: Setup Git and Restore Taxonomies
+      run: ./.github/scripts/setup_git.sh
+    - name: Rebuild taxonomies for Open Food Facts (off)
+      run: make DOCKER_LOCAL_DATA="$(pwd)" build_taxonomies GITHUB_TOKEN="${{ secrets.TAXONOMY_CACHE_GITHUB_TOKEN }}"
+    - name: Rebuild taxonomies for Open Beauty Facts (obf)
+      run: |
+        source env/setenv.sh obf
+        make DOCKER_LOCAL_DATA="$(pwd)" build_taxonomies GITHUB_TOKEN="${{ secrets.TAXONOMY_CACHE_GITHUB_TOKEN }}"
+    - name: Rebuild taxonomies for Open Products Facts (opf)
+      run: |
+        source env/setenv.sh opf
+        make DOCKER_LOCAL_DATA="$(pwd)" build_taxonomies GITHUB_TOKEN="${{ secrets.TAXONOMY_CACHE_GITHUB_TOKEN }}"
+    - name: Rebuild taxonomies for Open Pet Food Facts (opff)
+      run: |
+        source env/setenv.sh opff
+        make DOCKER_LOCAL_DATA="$(pwd)" build_taxonomies GITHUB_TOKEN="${{ secrets.TAXONOMY_CACHE_GITHUB_TOKEN }}"
 
   check_perl:
     name: 🐪 Check Perl
     needs: [build_backend]
     runs-on: ubuntu-latest
     steps:
-    - run: exit 1
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 1
+    - name: Setup Git and Restore Taxonomies
+      run: ./.github/scripts/setup_git.sh
+    - uses: actions/cache/restore@v4
+      id: cache
+      with:
+        path: ./build-cache
+        key: taxonomies-${{ hashFiles('taxonomies/**') }}
+        restore-keys: taxonomies-
+    - name: Download backend image from artifacts
+      id: downloadbackendimage
+      uses: ishworkh/container-image-artifact-download@v2.0.0
+      with:
+        image: "openfoodfacts-server/backend:dev"
+    # downloadbackendimage task loads the image into docker and keeps the original file.
+    # As our runs tend to hit the storage limits for GitHub Actions, manually delete the
+    # downloaded file for now. It's not needed after being loaded into docker.
+    - name: Remove downloaded image
+      env:
+        FILE: "${{ steps.downloadbackendimage.outputs.download_path }}"
+      run: rm $FILE
+    - name: build taxonomies (should use cache)
+      run: make DOCKER_LOCAL_DATA="$(pwd)" build_taxonomies GITHUB_TOKEN="${{ secrets.TAXONOMY_CACHE_GITHUB_TOKEN }}"
+    - name: check taxonomies
+      run: make check_taxonomies
+    - name: check perltidy
+      run: make check_perltidy
+    - name: check perlcritic
+      run: make check_critic
+    - name: check perl
+      run: make check_perl
 
   tests:
     name: 🐪 Perl unit tests
     needs: [build_backend]
     runs-on: ubuntu-latest
     steps:
-    - run: exit 1
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 1
+    - uses: actions/cache/restore@v4
+      id: cache
+      with:
+        path: ./build-cache
+        key: taxonomies-${{ hashFiles('taxonomies/**') }}
+        restore-keys: taxonomies-
+    - name: Setup Git and Restore Taxonomies
+      run: ./.github/scripts/setup_git.sh
+    - name: Download backend image from artifacts
+      id: downloadbackendimage
+      uses: ishworkh/container-image-artifact-download@v2.0.0
+      with:
+        image: "openfoodfacts-server/backend:dev"       
+    # downloadbackendimage task loads the image into docker and keeps the original file.
+    # As our runs tend to hit the storage limits for GitHub Actions, manually delete the
+    # downloaded file for now. It's not needed after being loaded into docker.
+    - name: Remove downloaded image
+      env:
+        FILE: "${{ steps.downloadbackendimage.outputs.download_path }}"
+      run: rm $FILE
+    - name: tests
+      run: |
+        make codecov_prepare
+        make COVER_OPTS='-e HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,tests/"' DOCKER_LOCAL_DATA="$(pwd)" tests GITHUB_TOKEN="${{ secrets.TAXONOMY_CACHE_GITHUB_TOKEN }}"
+    - name: generate coverage results
+      # even if tests failed
+      if: always()
+      run: |
+        make coverage_txt
+        make codecov
+    - uses: codecov/codecov-action@v5
+      if: always()
+      with:
+        files: cover_db/codecov.json
+        token: ${{ secrets.CODECOV_TOKEN }}
+    - name: Upload test results to Codecov
+      if: ${{ !cancelled() }}
+      uses: codecov/test-results-action@v1
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
+        files: ./tests/unit/outputs/junit.xml,./tests/integration/outputs/junit.xml
 
   tests_dev:
     name: 🧪 Test make dev
-    needs: [build_backend]
+    needs: [build_backend]  # build_backend - only to avoid building taxonomies
     runs-on: ubuntu-latest
+    
     steps:
-    - run: exit 1
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 1
+    - uses: actions/cache/restore@v4
+      id: cache
+      with:
+        path: ./build-cache
+        key: taxonomies-${{ hashFiles('taxonomies/**') }}
+        restore-keys: taxonomies-
+    - name: Download backend image from artifacts
+      id: downloadbackendimage
+      uses: ishworkh/container-image-artifact-download@v2.0.0
+      with:
+        image: "openfoodfacts-server/backend:dev"
+    # downloadbackendimage task loads the image into docker and keeps the original file.
+    # As our runs tend to hit the storage limits for GitHub Actions, manually delete the
+    # downloaded file for now. It's not needed after being loaded into docker.
+    - name: Remove downloaded image
+      env:
+        FILE: "${{ steps.downloadbackendimage.outputs.download_path }}"
+      run: rm $FILE
+    - name: set right UID and GID in .envrc
+      run: |
+        rm -f .envrc
+        echo "export USER_UID=$(id -u)" >> .envrc
+        echo "export USER_GID=$(id -g)" >> .envrc
+    - name: Test make dev
+      run: |
+        make DOCKER_LOCAL_DATA="$(pwd)" SKIP_SAMPLE_IMAGES=1 dev_no_build
+        make status
+    - name: Test all is running
+      run: make livecheck || ( tail -n 300 logs/apache2/*error*log; docker compose logs; false )
+    - name: test clean
+      run: make hdown
 
   test_deployment:
     name: 🦾 Some test of deployment tools
     runs-on: ubuntu-latest
     steps:
-    - run: exit 1
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 1
+    - name: verify apache2 envvars is correct
+      run: |
+        env/setenv.sh off;
+        sh -c ". conf/apache-2.4/off-envvars"
+        sh -c "APACHE_CONFDIR=/etc/apache2-priority; . conf/apache-2.4/off-envvars"
